version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app  
      - /app/node_modules 
    environment:
      - NODE_ENV=development
